[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "ArifRios1st"
name = "RepoCustomPhotonServer"
description = "Library for redirecting custom photon R.E.P.O server."
websiteUrl = "https://github.com/ArifRios1st/RepoCustomPhotonServer"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/RepoCustomPhotonServer/release/RepoCustomPhotonServer.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
communities = [ "repo", ]
[publish.categories]
repo = [ "mods", "tools", "misc", ]